# AUTOGENERATED! DO NOT EDIT! File to edit: ../../../nbs/07_l2r.models.core.ipynb.

# %% auto 0
__all__ = ['L2R_DotProductBias', 'L2R_NN', 'reshape_relevance_scores', 'log_print_output', 'fixed_approxNDCG_loss',
           'masked_approxNDCG_loss', 'LTRConfig', 'LTRModel']

# %% ../../../nbs/07_l2r.models.core.ipynb 2
import logging
import os
from typing import Optional, Dict
from fastai.torch_imports import *
from fastai.layers import *
# from xcube.layers import *
from transformers import AutoTokenizer, PretrainedConfig, PreTrainedModel, AutoConfig, AutoModel, AutoModelForCausalLM
from transformers import BitsAndBytesConfig
from safetensors.torch import load_file as load_safetensors
from peft import LoraConfig, get_peft_model
import sys
from io import StringIO
import io
import logging
from contextlib import redirect_stdout
from huggingface_hub import hf_hub_download
from ...utils import compute_trainable_params 

# %% ../../../nbs/07_l2r.models.core.ipynb 6
class L2R_DotProductBias(nn.Module):
    def __init__(self, num_lbs, num_toks, num_factors, y_range=None):
        super().__init__()
        self.num_toks, self.num_lbs = num_toks+1, num_lbs+1 # +1 for the `padding_idx` 
        self.num_factors = num_factors
        self.token_factors = nn.Embedding(self.num_toks, num_factors, padding_idx=-1)
        self.token_bias = nn.Embedding(self.num_toks, 1, padding_idx=-1)
        self.label_factors = nn.Embedding(self.num_lbs, num_factors, padding_idx=-1)
        self.label_bias = nn.Embedding(self.num_lbs, 1, padding_idx=-1)
        self.y_range = y_range
        
    def forward(self, xb):
        # import pdb; pdb.set_trace()
        xb_toks = xb[:, :, :, 0].long() # xb[...,0] # shape (64, 2233, 64)
        xb_lbs = torch.unique(xb[:, :, :, 1], dim=-1).flatten(start_dim=1).long() # shape (64, 2233, )
        # To convert -1 which is the padding index to the last index:
        xb_toks, xb_lbs= xb_toks%(self.num_toks), xb_lbs%(self.num_lbs)
        
        toks_embs = self.token_factors(xb_toks) # shape (64, 2233, 64, 400)
        toks_shape = toks_embs.shape
        toks_embs = toks_embs.view(-1, *toks_shape[2:]) # shape (64*2233, 64, 400)

        lbs_embs = self.label_factors(xb_lbs) # shape (64, 2233, 400)
        lbs_shape = lbs_embs.shape
        lbs_embs = lbs_embs.view(-1, *lbs_shape[2:]).unsqueeze(dim=-1) # shape (64*2233, 400, 1)
        
        # res = torch.bmm(toks_embs, lbs_embs) # shape (64*2233, 64, 1)
        # res = res.view(toks_shape[0], toks_shape[1], *res.shape[1:]) + self.token_bias(xb_toks) + self.label_bias(xb_lbs).unsqueeze(2) # shape (65, 2233, 64, 1)

        bias = self.token_bias(xb_toks) + self.label_bias(xb_lbs).unsqueeze(2) # (bs, lbs_in_one_chunk, sl, 1)
        bias = bias.view(-1, *bias.shape[2:]) # (bs*lbs_in_one_chunk, sl, 1)
        res = torch.baddbmm(bias, toks_embs, lbs_embs) # toks_embs: (bs*lbs_in_one_chunk, sl, emb_sz), lbs_embs: (bs*lbs_in_one_chunk, emb_sz, 1), res : (bs*lbs_in_one_chunk, sl, 1)
        res = res.view(toks_shape[0], toks_shape[1], *res.shape[1:]) # res (bs, lbs_in_one_chunk, sl, 1)
        
        return sigmoid_range(res, *self.y_range) if self.y_range is not None else res
        # return res

# %% ../../../nbs/07_l2r.models.core.ipynb 8
class L2R_NN(nn.Module):
    def __init__(self, num_lbs, 
                 num_toks, 
                 num_factors, 
                 layers,
                 ps=None,
                 use_bn=True,
                 bn_final=False,
                 lin_first=True,
                 embed_p=0.0,
                 y_range=None):
        super().__init__()
        self.num_toks, self.num_lbs = num_toks+1, num_lbs+1 # +1 for the `padding_idx` 
        self.num_factors, self.embed_p, self.ps = num_factors, embed_p, ps
        self.token_factors = nn.Embedding(self.num_toks, num_factors, padding_idx=-1)
        self.label_factors = nn.Embedding(self.num_lbs, num_factors, padding_idx=-1)
        self.emb_drop = nn.Dropout(embed_p)
        self.y_range = y_range
        if ps is None: self.ps = [0. for _ in range(len(layers))]
        sizes = [self.token_factors.embedding_dim] + layers + [1]
        actns = [nn.ReLU(inplace=True) for _ in range(len(sizes)-2)] + [None]
        _layers = [LinBnFlatDrop(sizes[i], sizes[i+1], bn=use_bn and (i!=len(actns)-1 or bn_final), p=p, act=a, lin_first=lin_first)
                   for i, (p,a) in enumerate(zip(self.ps+[0.],actns))]
        self.layers= nn.Sequential(*_layers)
        # self.layers = nn.Sequential(
        #     nn.Linear(num_factors, n_act),
        #     nn.ReLU(),
        #     nn.Linear(n_act, 1),
        #     nn.Dropout(self.ps),
        # )
        
    # def __str__(self): return super().__repr__() + f"\n {self.n_act = }, {self.embed_p = }"
    # __repr__ = __str__

    
    def forward(self, xb):
        # import pdb; pdb.set_trace()
        xb_toks = xb[:, :, :, 0].long() # xb[...,0] # shape (64, 2233, 64)
        xb_lbs = torch.unique(xb[:, :, :, 1], dim=-1).flatten(start_dim=1).long() # shape (64, 2233, )
        # To convert -1 which is the padding index to the last index:
        xb_toks, xb_lbs= xb_toks%(self.num_toks), xb_lbs%(self.num_lbs)
        
        toks_embs = self.token_factors(xb_toks) # shape (64, 2233, 64, 200)

        lbs_embs = self.label_factors(xb_lbs) # shape (64, 2233, 200)
        lbs_embs = lbs_embs.unsqueeze(2) # shape (64, 2233, 1, 200)
        lbs_embs = lbs_embs.expand(-1, -1, xb.shape[2], -1)
        
        # embs = torch.cat((toks_embs, lbs_embs), dim=-1) # shape (64, 2233, 64, 400)
        embs = toks_embs + lbs_embs
        embs = self.emb_drop(embs)
        res = self.layers(embs)
        
        return sigmoid_range(res, *self.y_range) if self.y_range is not None else res
        # return res

# %% ../../../nbs/07_l2r.models.core.ipynb 10
def reshape_relevance_scores(predicted_relevance_scores, true_relevance_scores):
    """
    Reshapes predicted and true relevance score tensors for relevance ranking tasks.

    Args:
        predicted_relevance_scores (torch.Tensor): Predicted relevance scores, shape (batch_size, max_len, num_labels)
        true_relevance_scores (torch.Tensor): Ground-truth relevance scores, shape (batch_size, max_len, num_labels)

    Returns:
        tuple: (reshaped_pred_scores, reshaped_true_scores) with shape (batch_size * num_labels, max_len) for each,
               where batch and label dimensions are combined for per-label sequence processing
    """
    batch_size, sequence_length, num_labels = predicted_relevance_scores.shape

    # Reshape to combine batch and label dimensions for per-label sequence processing
    reshaped_pred_scores = predicted_relevance_scores.permute(0, 2, 1).reshape(
        batch_size * num_labels, sequence_length
    )
    reshaped_true_scores = true_relevance_scores.permute(0, 2, 1).reshape(
        batch_size * num_labels, sequence_length
    )

    return reshaped_pred_scores, reshaped_true_scores

def log_print_output(func, *args, prefix="📊", **kwargs):
    """
    Capture print output from any function and log it

    Args:
        func: The function to call
        *args: Positional arguments to pass to the function
        prefix: Emoji/prefix for the log message
        **kwargs: Keyword arguments to pass to the function

    # Usage examples:
    log_print_output(model.print_trainable_parameters)
    log_print_output(print, "Hello World", prefix="🔍")
    log_print_output(some_function, arg1, arg2, keyword_arg=value, prefix="⚡")
    """
    with io.StringIO() as buf, redirect_stdout(buf):
        func(*args, **kwargs)
        output = buf.getvalue().strip()
        if output:  # Only log if there's actual output
            logging.info(f"{prefix} {output}")

# %% ../../../nbs/07_l2r.models.core.ipynb 11
from ptranking.ltr_adhoc.listwise.approxNDCG import get_approx_ranks
from ptranking.ltr_adhoc.eval.eval_utils import LABEL_TYPE
from ptranking.metric.adhoc_metric import torch_dcg_at_k
from torch.nn.init import trunc_normal_


def _approx_ndcg_per_row(batch_preds, batch_stds, alpha=10, label_type=None, gpu=False):
    """
    One approxNDCG value per row of (batch_preds, batch_stds).

    This exists because ptranking's own approxNDCG_loss has a shape bug: it
    divides batch_dcg (shape (num_rows,)) by batch_idcgs (shape
    (num_rows, 1), since torch_dcg_at_k uses keepdim=True) without
    squeezing the trailing dim first, so the division broadcasts to
    (num_rows, num_rows) -- result[i, j] = batch_dcg[j] / batch_idcgs[i].
    Only the diagonal (i == j) is the mathematically correct per-row nDCG;
    every off-diagonal entry divides one row's DCG by an unrelated row's
    IDCG. approxNDCG_loss's final -torch.mean(...) then averages over all
    num_rows**2 entries instead of the intended num_rows, diluting the
    correct signal with nonsensical cross-terms. This affected every
    approxNDCG_loss call site in this repo (Stage 2's classifier heads,
    LTRModel) before this fix -- see README_AMAZON3M.md for the full
    writeup. Squeezing batch_idcgs before dividing avoids ever forming
    that (num_rows, num_rows) matrix in the first place.
    """
    batch_hat_pis = get_approx_ranks(batch_preds, alpha=alpha, gpu=gpu)
    batch_idcgs = torch_dcg_at_k(
        batch_sorted_labels=batch_stds, cutoff=None, label_type=label_type, gpu=gpu
    ).squeeze(-1)

    if LABEL_TYPE.MultiLabel == label_type:
        batch_gains = torch.pow(2.0, batch_stds) - 1.0
    elif LABEL_TYPE.Permutation == label_type:
        batch_gains = batch_stds
    else:
        raise NotImplementedError

    batch_dcg = torch.sum(torch.div(batch_gains, torch.log2(batch_hat_pis + 1)), dim=1)
    return torch.div(batch_dcg, batch_idcgs)  # (num_rows,), one correct nDCG per row


def fixed_approxNDCG_loss(batch_preds, batch_stds, alpha=10, label_type=None, gpu=False):
    """
    Drop-in, correctly-shaped replacement for ptranking's approxNDCG_loss --
    see _approx_ndcg_per_row's docstring for the shape bug this fixes.
    """
    batch_approx_nDCG = _approx_ndcg_per_row(
        batch_preds, batch_stds, alpha=alpha, label_type=label_type, gpu=gpu
    )
    return -torch.mean(batch_approx_nDCG)


def masked_approxNDCG_loss(batch_preds, batch_stds, row_mask, alpha=10, label_type=None, gpu=False):
    """
    Like fixed_approxNDCG_loss, but averages only over rows where row_mask
    is True instead of every row.

    LTRModel.forward() reshapes (batch_size, max_len, n) into
    (batch_size * n, max_len) rows -- one row per (example, candidate-slot)
    pair, ranking that pair's own token sequence. A fixed-size candidate
    budget (see the full-scale candidate-generator plan, README_AMAZON3M.md)
    pads docs with fewer true+hard-negative candidates than the budget
    width, so some of those rows are pure padding, not real (example,
    label) pairs -- this excludes them from the mean instead of averaging
    them in.

    Args:
        batch_preds, batch_stds: (num_rows, ranking_size), same as fixed_approxNDCG_loss.
        row_mask: (num_rows,) bool/float tensor, True/1 for real (non-padding) rows.
    """
    batch_approx_nDCG = _approx_ndcg_per_row(
        batch_preds, batch_stds, alpha=alpha, label_type=label_type, gpu=gpu
    )
    row_mask = row_mask.to(batch_approx_nDCG.dtype)
    denom = torch.clamp(row_mask.sum(), min=1.0)
    return -torch.sum(batch_approx_nDCG * row_mask) / denom

# %% ../../../nbs/07_l2r.models.core.ipynb 12
class LTRConfig(PretrainedConfig):
    model_type = "ltr_model"

    def __init__(self, num_labels=7942, ground_model_name_or_path=None, label_embed_rank=None, **kwargs):
        super().__init__(**kwargs)
        # Register additional attributes
        self.num_labels = num_labels
        self.ground_model_name_or_path = (
            ground_model_name_or_path or "mistralai/Mistral-7B-Instruct-v0.3"
        )
        # Factorized label embeddings (see LTRModel.__init__) -- None keeps the
        # original full-rank (num_labels, hidden_size) table, used when
        # num_labels is bounded (e.g. a cluster-router). Set this for the full
        # ~2.81M-label Amazon-3M vocabulary (see README_AMAZON3M.md's
        # full-scale candidate-generator plan).
        self.label_embed_rank = label_embed_rank


class LTRModel(PreTrainedModel):
    """
    Learning-to-Rank model based on a pretrained transformer, outputting per-token relevance scores per label
    using label embeddings and matrix multiplication.

    Args:
        base_model (AutoModelForCausalLM): Pretrained transformer model.
        num_labels (int): Number of labels for relevance scoring.
    """

    config_class = LTRConfig

    def __init__(self, config):
        super().__init__(config)
        self.num_labels = config.num_labels
        self.hidden_size = config.hidden_size
        self.label_embed_rank = getattr(config, "label_embed_rank", None)
        # Label embeddings. A full-rank (num_labels, hidden_size) table is only
        # safe when num_labels is bounded (e.g. this model's own cluster-router
        # mode) -- at Amazon-3M's full ~2.81M-label scale it's tens of GB of
        # parameters plus optimizer state before any forward pass even runs.
        # label_embed_rank, when set, factorizes it into a small
        # (num_labels, label_embed_rank) base table plus one shared
        # up-projection to hidden_size, per the full-scale candidate-generator
        # plan (see README_AMAZON3M.md).
        if self.label_embed_rank:
            self.label_embeddings = nn.Embedding(self.num_labels, self.label_embed_rank)
            self.label_up_proj = nn.Linear(self.label_embed_rank, self.hidden_size, bias=False)
            trunc_normal_(self.label_embeddings.weight, std=0.01)
            trunc_normal_(self.label_up_proj.weight, std=0.01)
        else:
            self.label_embeddings = nn.Embedding(self.num_labels, self.hidden_size)
            self.label_up_proj = None
            trunc_normal_(self.label_embeddings.weight, std=0.01)

        # Initialize ground model as None (will be set in from_pretrained)
        self.ground_model = None
        # Initialize lookup table
        self.lookup_table = None

    def _init_ground_model(self, config, quantization_config=None):
        """Initialize the ground model with pretrained weights and apply LoRA."""
        try:
            model_name = config.ground_model_name_or_path

            # Determine model type and load appropriately
            logging.info(f"🧠 Loading ground model {model_name} with quantization...")
            if "bert" in model_name.lower():
                # BERT-based models use AutoModel
                self.ground_model = AutoModel.from_pretrained(
                    model_name,
                    quantization_config=quantization_config,
                    device_map="auto",
                    trust_remote_code=True,
                    torch_dtype=torch.bfloat16,
                )
            else:
                # Default to causal LM for models like Mistral
                self.ground_model = AutoModelForCausalLM.from_pretrained(
                    model_name,
                    quantization_config=quantization_config,
                    device_map="auto",
                    trust_remote_code=True,
                    torch_dtype=torch.bfloat16,
                )
            logging.info(f"✅ Ground model loaded from {model_name}")

            # Define default LoRA configuration based on model type
            lora_config = None
            logging.info("🔧 Setting up default LoRA configuration...")
            if "bert" in model_name.lower():
                # LoRA config for BERT-based models
                lora_config = LoraConfig(
                    r=16,
                    lora_alpha=32,
                    target_modules=["query", "key", "value", "output.dense"],
                    lora_dropout=0.05,
                    bias="none",
                    task_type="MASKED_LM",
                )
            else:
                # LoRA config for causal LM models
                # Phi-3-mini/medium fuse q/k/v into qkv_proj; Phi-3-small
                # (loaded via trust_remote_code from Microsoft's own
                # modeling_phi3_small.py) uses a differently-named fused
                # query_key_value/dense pair. Both differ from Llama/
                # Mistral's separate q_proj/k_proj/v_proj/o_proj. Mirrors
                # the model_type branching in learning2rank.py's
                # load_base_model_and_tokenizer -- self.ground_model is
                # already loaded above, so its config.model_type is the
                # canonical signal, more robust than matching on model_name
                # (a free-form Hub id string).
                ground_model_type = getattr(
                    self.ground_model.config, "model_type", ""
                ).lower()
                if ground_model_type == "phi3":
                    target_modules = ["qkv_proj", "o_proj"]
                elif ground_model_type == "phi3small":
                    target_modules = ["query_key_value", "dense"]
                else:
                    target_modules = ["q_proj", "k_proj", "v_proj", "o_proj"]
                lora_config = LoraConfig(
                    r=16,
                    lora_alpha=32,
                    target_modules=target_modules,
                    lora_dropout=0.05,
                    bias="none",
                    task_type="CAUSAL_LM",
                )

            # Log LoRA configuration
            logging.info(
                f"🔍 LoRA config: r={lora_config.r}, alpha={lora_config.lora_alpha}, "
                f"targets={lora_config.target_modules}, dropout={lora_config.lora_dropout}"
            )

            # Apply LoRA
            logging.info("🧩 Applying LoRA adapters to ground model...")
            self.ground_model = get_peft_model(self.ground_model, lora_config)
            log_print_output(func=self.ground_model.print_trainable_parameters)
            log_print_output(compute_trainable_params, self.ground_model)

        except Exception as e:
            logging.error(f"❌ Error initializing ground model: {e}")
            raise RuntimeError(f"Ground model initialization failed: {e}")

    def forward_old(
        self, input_ids: torch.Tensor, attention_mask: torch.Tensor
    ) -> torch.Tensor:
        """
        Forward pass to compute per-token relevance scores per label.

        Args:
            input_ids (torch.Tensor): Shape (batch_size, max_len).
            attention_mask (torch.Tensor): Shape (batch_size, max_len).

        Returns:
            torch.Tensor: Relevance scores of shape (batch_size, max_len, num_labels).
        """
        outputs = self.base_model(
            input_ids=input_ids,
            attention_mask=attention_mask,
            output_hidden_states=True,
        )
        # hidden_states = outputs.hidden_states[-1]  # Shape: (batch_size, max_len, hidden_size)
        hidden_states = (
            outputs.last_hidden_state
        )  # Shape: (batch_size, max_len, hidden_size)
        relevance_scores = self.relevance_head(
            hidden_states
        )  # Shape: (batch_size, max_len, num_labels)
        return relevance_scores

    def forward(
        self,
        input_ids: torch.Tensor,
        attention_mask: torch.Tensor,
        labels: Optional[torch.Tensor] = None,
        candidate_label_ids: Optional[torch.Tensor] = None,
        candidate_mask: Optional[torch.Tensor] = None,
        **kwargs,
    ) -> Dict[str, torch.Tensor]:
        """
        Forward pass to compute per-token relevance scores per label using matrix multiplication
        between token hidden states and label embeddings.

        Args:
            input_ids (torch.Tensor): Shape (batch_size, max_len).
            attention_mask (torch.Tensor): Shape (batch_size, max_len).
            labels (torch.Tensor, optional): Ground-truth relevance scores, shape (batch_size, max_len, num_labels).
            candidate_label_ids (torch.Tensor, optional): Per-example label ids to score
                against, shape (batch_size, budget), instead of every one of self.num_labels
                labels. This is the mechanism that keeps training tractable at Amazon-3M's
                full ~2.81M-label scale (see README_AMAZON3M.md's full-scale
                candidate-generator plan) -- a single batch never needs to hold a
                (batch_size, max_len, num_labels) tensor at full label-space width. Omit to
                keep scoring every label, as before (e.g. for a bounded cluster-router
                num_labels).
            candidate_mask (torch.Tensor, optional): Shape (batch_size, budget), True where
                candidate_label_ids is a real candidate and False where it's padding (a
                fixed-size budget usually has fewer real candidates -- true positives plus
                same-cluster hard negatives -- than its width). Only meaningful together with
                candidate_label_ids; ignored otherwise.

        Returns:
            torch.Tensor: Relevance scores of shape (batch_size, max_len, num_labels_or_budget).
        """
        if self.ground_model is None:
            raise ValueError(
                "ground_model is not initialized. Ensure it is set before calling forward."
            )

        outputs = self.ground_model(
            input_ids=input_ids,
            attention_mask=attention_mask,
            output_hidden_states=True,
        )
        hidden_states = outputs.hidden_states[
            -1
        ]  # Shape: (batch_size, max_len, hidden_size) # mistrals
        # hidden_states = outputs.last_hidden_state  # Shape: (batch_size, max_len, hidden_size) # bert-based

        # Score every label by default; a per-example candidate_label_ids restricts
        # scoring to just those ids instead (see the docstring above).
        batch_size = hidden_states.size(0)
        if candidate_label_ids is not None:
            label_ids = candidate_label_ids  # (batch_size, budget)
        else:
            label_ids = (
                torch.arange(self.num_labels, device=hidden_states.device)
                .unsqueeze(0)
                .expand(batch_size, -1)
            )  # (batch_size, num_labels)

        label_base = self.label_embeddings(label_ids)  # (batch_size, n, label_embed_rank or hidden_size)
        label_queries = (
            self.label_up_proj(label_base) if self.label_up_proj is not None else label_base
        )  # (batch_size, n, hidden_size)

        # Compute relevance scores via matrix multiplication
        # hidden_states: (batch_size, max_len, hidden_size)
        # label_queries.transpose: (batch_size, hidden_size, n)
        # Result: (batch_size, max_len, n)
        predicted_relevance_scores = torch.bmm(
            hidden_states, label_queries.transpose(1, 2)
        )  # Shape: (batch_size, max_len, n)

        output_dict = {"logits": predicted_relevance_scores}

        # Add hidden_states
        output_dict["hidden_states"] = hidden_states

        if self.lookup_table is not None:
            if candidate_label_ids is not None:
                # Gather lookup_table[input_ids[b, t], candidate_label_ids[b, k]] directly via
                # paired advanced indexing -- NOT lookup_table[input_ids, :] followed by a
                # column gather, which would materialize a (batch_size, max_len, num_labels)
                # intermediate at full label-space width before narrowing to the budget,
                # defeating the entire point of candidate restriction.
                max_len = input_ids.size(1)
                budget = candidate_label_ids.size(1)
                tok_idx = input_ids.unsqueeze(-1).expand(-1, -1, budget)
                cand_idx = candidate_label_ids.unsqueeze(1).expand(-1, max_len, -1)
                true_relevance_scores = self.lookup_table[tok_idx, cand_idx].to(hidden_states.device)
            else:
                # Ground-truth relevance scores, shape (batch_size, max_len, num_labels)
                true_relevance_scores = self.lookup_table[input_ids, :].to(hidden_states.device)
            output_dict["labels"] = true_relevance_scores

            # Compute loss
            # loss1 = lambdarank_loss(predicted_relevance_scores, true_relevance_scores)
            predicted_relevance_scores, true_relevance_scores = reshape_relevance_scores(
                predicted_relevance_scores, true_relevance_scores
            )
            # true_relevance_scores are fine-grained quantile-bin grades (0-101,
            # see quantize_l2r_data), not the handful of LETOR-style relevance
            # levels LABEL_TYPE.MultiLabel's exponential gain (2^rel - 1) assumes.
            # LABEL_TYPE.Permutation uses linear gains (batch_stds as-is), which
            # stays numerically stable across the full grade range.
            if candidate_mask is not None:
                # Each row post-reshape is one (example, candidate-slot) pair, ranking
                # that pair's own token sequence -- padding means the whole row is fake,
                # not that some entries within it are, so masking means excluding whole
                # rows from the loss's mean, not masking individual entries (see
                # masked_approxNDCG_loss's docstring).
                row_mask = candidate_mask.reshape(-1)
                loss = masked_approxNDCG_loss(
                    batch_preds=predicted_relevance_scores,
                    batch_stds=true_relevance_scores,
                    row_mask=row_mask,
                    label_type=LABEL_TYPE.Permutation,
                    gpu=torch.cuda.is_available(),
                )
            else:
                loss = fixed_approxNDCG_loss(
                    batch_preds=predicted_relevance_scores,
                    batch_stds=true_relevance_scores,
                    label_type=LABEL_TYPE.Permutation,
                    gpu=torch.cuda.is_available(),
                )
            output_dict["loss"] = loss

        return output_dict

    def compute_trainable_params(self):
        trainable_params = sum(p.numel() for p in self.parameters() if p.requires_grad)
        total_params = sum(p.numel() for p in self.parameters())
        trainable_percentage = 100 * trainable_params / total_params

        logging.info(
            f"📊 trainable params: {trainable_params:,} || all params: {total_params:,} || trainable%: {trainable_percentage:.4f}"
        )
        return trainable_params, total_params

    def save_pretrained(self, save_directory, **kwargs):
        """Override save_pretrained to include ground_model and lookup_table."""
        os.makedirs(save_directory, exist_ok=True)
        super().save_pretrained(save_directory, **kwargs)
        if self.ground_model is not None:
            # Hardcode safe_serialization=False here rather than forwarding
            # it from kwargs: ground_model is the base LLM, which for
            # Phi-3-small ties embed_tokens/lm_head (tie_word_embeddings=
            # True, unlike Mistral/Llama), and safetensors can't serialize
            # tensors that share memory. torch.save (pytorch_model.bin)
            # handles aliased tensors natively. Harmless no-op for
            # untied Mistral/Llama.
            self.ground_model.save_pretrained(
                os.path.join(save_directory, "ground_model"),
                safe_serialization=False,
            )
        if self.lookup_table is not None:
            torch.save(
                self.lookup_table, os.path.join(save_directory, "lookup_table.pt")
            )
        logging.info(
            f"✅ Model, ground_model, and lookup_table saved to {save_directory}"
        )

    @classmethod
    def from_pretrained(cls, pretrained_model_name_or_path, *model_args, device_map="cpu", **kwargs):
        """Override from_pretrained to load weights from model.safetensors or pytorch_model.bin."""

        device = "cuda" if torch.cuda.is_available() else "cpu"

        config = LTRConfig.from_pretrained(
            pretrained_model_name_or_path, *model_args, **kwargs
        )
        model = cls(config)

        # Initialize ground model with LoRA
        # quantization_config = kwargs.get("quantization_config", None)
        model._init_ground_model(config, quantization_config=config.quantization_config)

        # Move model to specified device
        model = model.to(device)
        logging.info(f"🖥️ Model moved to device: {device}")

        # Load from a local directory if given one; otherwise download from the Hub.
        # hf_hub_download requires a namespace/repo_name id and raises HFValidationError
        # on a local path, so that branch must never be taken for on-disk checkpoints
        # (e.g. Stage 4's local L2R output loaded as Stage 5's --hub_model_id).
        custom_state_dict = None
        hf_token = kwargs.get("token", None)
        is_local = os.path.isdir(pretrained_model_name_or_path)

        safetensors_path = os.path.join(pretrained_model_name_or_path, "model.safetensors")
        try:
            if is_local:
                if not os.path.exists(safetensors_path):
                    raise FileNotFoundError(safetensors_path)
            else:
                safetensors_path = hf_hub_download(
                    repo_id=pretrained_model_name_or_path,
                    filename="model.safetensors",
                    token=hf_token,
                )
            custom_state_dict = load_safetensors(safetensors_path)
            logging.info(f"✅ Loaded model weights from {safetensors_path}")
        except Exception as e:
            logging.warning(
                f"❌ Failed to load model.safetensors: {e}, trying pytorch_model.bin"
            )

        if custom_state_dict is None:
            pytorch_bin_path = os.path.join(pretrained_model_name_or_path, "pytorch_model.bin")
            try:
                if is_local:
                    if not os.path.exists(pytorch_bin_path):
                        raise FileNotFoundError(pytorch_bin_path)
                else:
                    pytorch_bin_path = hf_hub_download(
                        repo_id=pretrained_model_name_or_path,
                        filename="pytorch_model.bin",
                        token=hf_token,
                    )
                custom_state_dict = torch.load(pytorch_bin_path, map_location="cpu")
                logging.info(f"✅ Loaded model weights from {pytorch_bin_path}")
            except Exception as e:
                logging.error(f"❌ Failed to load pytorch_model.bin: {e}")
                raise

        if custom_state_dict is None:
            logging.error(
                f"❌ No valid model weights found in {pretrained_model_name_or_path}"
            )
            raise FileNotFoundError(
                f"No model.safetensors or pytorch_model.bin found in {pretrained_model_name_or_path}"
            )

        # Move tensors to the specified device
        custom_state_dict = {k: v.to(device) for k, v in custom_state_dict.items()}

        # Align state_dict keys with model's expected order
        model_state_dict = model.state_dict()
        if set(custom_state_dict.keys()) != set(model_state_dict.keys()):
            logging.warning(
                f"⚠️ Key mismatch: loaded keys {set(custom_state_dict.keys())} != model keys {set(model_state_dict.keys())}"
            )
        ordered_state_dict = {
            k: custom_state_dict[k]
            for k in model_state_dict.keys()
            if k in custom_state_dict
        }

        # Load weights
        model.load_state_dict(ordered_state_dict, strict=False)
        logging.info(f"✅ Custom weights loaded into model")

        # Verify weights match
        weights_match = True
        for key in list(model_state_dict.keys())[:2]:  # Check first two parameters
            if key in custom_state_dict and not torch.equal(
                custom_state_dict[key], model_state_dict[key]
            ):
                logging.warning(f"⚠️ Weight mismatch for {key}")
                weights_match = False
        if weights_match:
            logging.info(f"✔️ Loaded weights match model's state_dict")
        else:
            logging.warning(f"⚠️ Some loaded weights do not match model's state_dict")

        # Load lookup table
        try:
            lookup_table_path = os.path.join(pretrained_model_name_or_path, "lookup_table.pt")
            if is_local:
                if not os.path.exists(lookup_table_path):
                    raise FileNotFoundError(lookup_table_path)
            else:
                lookup_table_path = hf_hub_download(
                    repo_id=pretrained_model_name_or_path,
                    filename="lookup_table.pt",
                    token=hf_token,
                )
            model.lookup_table = torch.load(lookup_table_path, map_location=device)
            logging.info(f"✅ Lookup table loaded from {lookup_table_path}")
        except Exception as e:
            logging.error(
                f"❌ Error loading lookup table from {pretrained_model_name_or_path}: {e}"
            )
            raise

        logging.info("🧩 After loading the pretrained weights...")
        log_print_output(func=model.compute_trainable_params)

        return model
