"""with the excellent library BERTopic"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/20_text.topicmodel.ipynb.

# %% auto 0
__all__ = ['get_topic_model', 'get_topicsmap', 'print_representative_topics', 'get_topic', 'print_top_topics', 'save_topic_model']

# %% ../../nbs/20_text.topicmodel.ipynb 1
# from fastai.torch_imports import *
# from fastai.torch_core import *
# from fastai.callback.core import *
# from fastcore.all import *
from ..imports import *
from datasets import load_dataset, load_from_disk 
from nltk.tokenize import sent_tokenize, word_tokenize

# %% ../../nbs/20_text.topicmodel.ipynb 6
from umap import UMAP
from hdbscan import HDBSCAN
from sentence_transformers import SentenceTransformer
from sklearn.feature_extraction.text import CountVectorizer

from bertopic import BERTopic
from bertopic.representation import KeyBERTInspired, MaximalMarginalRelevance, OpenAI, PartOfSpeech

from bertopic.vectorizers import ClassTfidfTransformer
import openai

# %% ../../nbs/20_text.topicmodel.ipynb 7
def get_topic_model(embedding_model="all-MiniLM-L6-v2",
                    umap_n_neighbors=15, umap_n_components=5, umap_min_dist=0.0, umap_metric='cosine',
                    hdbscan_min_cluster_size=15, hdbscan_metric='euclidean', hdbscan_cluster_selection_method='eom',
                    vectorizer_stop_words="english",
                    representation_model=None,
                    random_state=None,
                    low_memory=False,
                    openai_API_KEY=None,
                    **kwargs):
    
    # Step 1 - Extract embeddings
    embedding_model = SentenceTransformer(embedding_model)
    
    # Step 2 - Reduce dimensionality
    umap_model = UMAP(n_neighbors=umap_n_neighbors, n_components=umap_n_components, min_dist=umap_min_dist, metric=umap_metric, random_state=random_state, low_memory=low_memory)

    # Step 3 - Cluster reduced embeddings
    hdbscan_model = HDBSCAN(min_cluster_size=hdbscan_min_cluster_size, metric=hdbscan_metric, cluster_selection_method=hdbscan_cluster_selection_method, prediction_data=True)

    # Step 4 - Tokenize topics
    vectorizer_model = CountVectorizer(stop_words=vectorizer_stop_words, min_df=2, ngram_range=(1,2))

    # Step 5 - Create topic representation
    ctfidf_model = ClassTfidfTransformer()

    # Step 6 - (Optional) Fine-tune topic representations with a `bertopic.representation` model
    # KeyBERT
    keybert_model = KeyBERTInspired()

    # GPT-3.5
    if openai_API_KEY:
        client = openai.OpenAI(api_key=openai_API_KEY)
        prompt = """
        I have a topic that contains the following documents: 
        [DOCUMENTS]
        The topic is described by the following keywords: [KEYWORDS]

        Based on the information above, extract a short but highly descriptive topic label of at most 5 words. Make sure it is in the following format:
        topic: <topic label>
        """
        openai_model = OpenAI(client, model="gpt-4o-mini", exponential_backoff=True, chat=True, prompt=prompt)
    representation_model = {
        "KeyBERT": keybert_model,
        # "OpenAI": openai_model if openai_API_KEY else None,  # Uncomment if you will use OpenAI
    }

    # Conditionally add OpenAI model if the API key is available
    if openai_API_KEY:
        representation_model["OpenAI"] = openai_model
    
    # All steps together
    topic_model = BERTopic(embedding_model=embedding_model,
                           umap_model=umap_model,
                           hdbscan_model=hdbscan_model,
                           vectorizer_model=vectorizer_model,
                           ctfidf_model=ctfidf_model,
                           representation_model=representation_model,
                           verbose=True,
                           low_memory=low_memory,
                           **kwargs
                           )

    return embedding_model, topic_model
 

# %% ../../nbs/20_text.topicmodel.ipynb 24
def get_topicsmap(df_topics):
    """
    Creates a dictionary mapping topics to their corresponding names.

    Args:
    - df_topics (pandas.DataFrame): A DataFrame containing topic information.
        It should have at least two columns: 'Topic' and 'Name'.

    Returns:
    - dict: A dictionary where the keys are topic numbers and the values are
        the corresponding names of the topics.
    """
    return dict(zip(df_topics['Topic'], df_topics['CustomName']))


# %% ../../nbs/20_text.topicmodel.ipynb 26
def print_representative_topics(df, topic_num):
    """
    Print representative topics for a specified topic number.

    Args:
        df (DataFrame): The pandas DataFrame containing the topics and representative documents, obtained by `topic_model.get_topic_info()`.
        topic_num (int): The topic number for which representative topics should be printed.

    Returns:
        None

    Example:
        >>> print_representative_topics(df, 2)
    """
    filtered_topic = df[df['Topic'] == topic_num].iloc[0]
    print(f"Representative docs for Topic {topic_num}, that is \"{filtered_topic['Name']}\":")
    for doc in filtered_topic['Representative_Docs']:
        print(doc)
        print("****************")


# %% ../../nbs/20_text.topicmodel.ipynb 28
def get_topic(topic_model, topic_num):
    print('\n'.join(L(topic_model.get_topic(topic_num, full=False)).map(lambda pair: f"{pair[0]} --> {pair[1]}")))

# %% ../../nbs/20_text.topicmodel.ipynb 35
def print_top_topics(topic_model, description, topics_map, top_n=5):
    """
    Prints the top N topics related to a given description.

    Args:
    - topic_model (BERTopic): A BERTopic model instance.
    - description (str): The description for which top topics are to be found.
    - topics_map (dict): A dictionary mapping topic numbers to their corresponding names.
    - top_n (int, optional): The number of top topics to print. Defaults to 5.

    Returns:
    None
    """
    similar_topics, similarity = topic_model.find_topics(description, top_n=top_n)
    print(f'The top {top_n} topics for the description are:')
    for i, (topic, sim) in enumerate(zip(similar_topics, similarity)):
        print(f"{i}: {topics_map.get(topic, None)}, similarity is {sim}")
        get_topic(topic_model, topic)
        print("**********************")


# %% ../../nbs/20_text.topicmodel.ipynb 39
def save_topic_model(topic_model, path, embedding_model_name=None):
    """
    Saves the topic model to the specified path, including the embedding model.

    Args:
    - topic_model (BERTopic): A BERTopic model instance.
    - path (str): The path where the model will be saved.
    - embedding_model: The embedding model used in the topic model.

    Returns:
    None
    """
    if embedding_model_name: print(f"Saving the embedding model {embedding_model_name} along with topic_model.")
    topic_model.save(path, serialization="safetensors", save_ctfidf=True, save_embedding_model=embedding_model_name)
